export type TransactionType = 'LOAD' | 'TRANSFER' | 'REDEEM'
export type OperationType = 'SPLIT' | 'MERGE' | 'ISSUE'
export type ErrorCode = 'No error' | 'AS400' | 'AS401' | 'AS402' | 'AS403' | 'AS404' | 'AS405' | 'AS406' | 'AS500' | 'AS503'
export type TransactionResult = 'success' | 'failure'
export type ErrorMessage = '' | 'Unauthorized Access' | 'Invalid Inputs - Token Issuer Signature Failed' | 'Invalid Input - Token Duplicate' | 'Invalid Input - Output Format' | 'Mismatch Input Output Balance' | 'Exceed Maximum Input Length' | 'Exceed Maximum Output Length' | 'Processing Error' | 'Service Unavailable - Try Again After Sometime'